

create-channel:
	./bin/configtxgen -profile Channel -outputCreateChannelTx composerchannel.tx -channelID composerchannel

genesisBlock:
	./bin/configtxgen -profile OrdererGenesis -outputBlock ./genesis.block