#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  ca.trt.xuyuntech.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-trt
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.trt.xuyuntech.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/22c6a29cda62a7988f51ec455bb5520de56a743bdd24fdc8cdcc8fe4d8ae6b29_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.trt.xuyuntech.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/22c6a29cda62a7988f51ec455bb5520de56a743bdd24fdc8cdcc8fe4d8ae6b29_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
      - ./channel/crypto-config/peerOrganizations/trt.xuyuntech.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca
    depends_on:
    - postgres

  # ca.org2.example.com:
  #   image: hyperledger/fabric-ca
  #   environment:
  #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  #     - FABRIC_CA_SERVER_CA_NAME=ca-org2
  #     - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
  #     - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/a7d47efa46a6ba07730c850fed2c1375df27360d7227f48cdc2f80e505678005_sk
  #     - FABRIC_CA_SERVER_TLS_ENABLED=true
  #     - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
  #     - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/a7d47efa46a6ba07730c850fed2c1375df27360d7227f48cdc2f80e505678005_sk
  #   ports:
  #     - "8054:7054"
  #   command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
  #   volumes:
  #     - ./channel/crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
  #   container_name: ca_peerOrg2
  postgres:
    container_name: postgres
    image: postgres:9-alpine
    environment:
    - POSTGRES_USER=fabric
    - POSTGRES_PASSWORD=fabricpw
    - POSTGRES_DB=fabric_ca
    # volumes:
    # - ./db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  orderer.xuyuntech.com:
    container_name: orderer
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt, /etc/hyperledger/crypto/peerTrt/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./channel:/etc/hyperledger/configtx
        - ./channel/crypto-config/ordererOrganizations/xuyuntech.com/orderers/orderer.xuyuntech.com/:/etc/hyperledger/crypto/orderer
        - ./channel/crypto-config/peerOrganizations/trt.xuyuntech.com/peers/peer0.trt.xuyuntech.com/:/etc/hyperledger/crypto/peerTrt

  peer0.trt.xuyuntech.com:
    container_name: peer0
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.trt.xuyuntech.com
      - CORE_PEER_LOCALMSPID=TrtMSP
      - CORE_PEER_ADDRESS=peer0.trt.xuyuntech.com:7051
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/trt.xuyuntech.com/peers/peer0.trt.xuyuntech.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.xuyuntech.com

  # peer1.trt.xuyuntech.com:
  #   container_name: peer1.org1.example.com
  #   extends:
  #     file:   base.yaml
  #     service: peer-base
  #   environment:
  #     - CORE_PEER_ID=peer1.org1.example.com
  #     - CORE_PEER_LOCALMSPID=Org1MSP
  #     - CORE_PEER_ADDRESS=peer1.org1.example.com:7051
  #   ports:
  #     - 7056:7051
  #     - 7058:7053
  #   volumes:
  #       - ./channel/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/:/etc/hyperledger/crypto/peer
  #   depends_on:
  #     - orderer.example.com

  # peer0.org2.example.com:
  #   container_name: peer0.org2.example.com
  #   extends:
  #     file:   base.yaml
  #     service: peer-base
  #   environment:
  #     - CORE_PEER_ID=peer0.org2.example.com
  #     - CORE_PEER_LOCALMSPID=Org2MSP
  #     - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
  #   ports:
  #     - 8051:7051
  #     - 8053:7053
  #   volumes:
  #       - ./channel/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/:/etc/hyperledger/crypto/peer
  #   depends_on:
  #     - orderer.example.com

  # peer1.org2.example.com:
  #   container_name: peer1.org2.example.com
  #   extends:
  #     file:   base.yaml
  #     service: peer-base
  #   environment:
  #     - CORE_PEER_ID=peer1.org2.example.com
  #     - CORE_PEER_LOCALMSPID=Org2MSP
  #     - CORE_PEER_ADDRESS=peer1.org2.example.com:7051
  #   ports:
  #     - 8056:7051
  #     - 8058:7053
  #   volumes:
  #       - ./channel/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/:/etc/hyperledger/crypto/peer
  #   depends_on:
  #     - orderer.example.com
